# Limitation for arms
min_x_arm: -600
max_x_arm: 600
min_y_arm: 0
max_y_arm: 600
min_z_arm: 0
max_z_arm: 500

# Limitation for arm speed
arm_max_speed: 5
arm_min_speed: 0.1
        
# Limitation for the end effector
min_x_end_effector: 0
max_x_end_effector: 180

# Home position for the arms 
home_position_x: 0
home_position_y: 200
home_position_z: 300

# End position for the arms
end_position_x: 0
end_position_y: 200
end_position_z: 500

# Prew set path for the arms, where the first value is the x position, the second is the y position and the third is the z position
arm_movement: [[0, 200, 300],[0, 200, 400],[0, 200, 500],[0, 200, 200],[100, 200, 400]]
<<<<<<< HEAD
endeff_movement: [[90, 90],[60, 60],[120, 60],[120, 120],[60, 120],[90, 90]]
=======
# Prew set path for the end effectors, where the first value is tilt(second servo) and the second is pan(first servo)
endeff_movement: [[90, 90],[60, 90],[60, 120],[90, 120],[120, 120],[120, 90],[120, 60],[90, 60],[60, 60],[60, 90],[90, 90]]
>>>>>>> b10cc71... test

# Params for the sinusodal movement, where the first value is the start and end position for the x axis, the second is the speed for the x axis, the third is the y position
sinus_x_start_end: [-150, 250]
sinus_speed_x: 1
sinus_y: 200

# Params for the cosinusodal movement, where the first value is the start and end position for the x axis, the second is the speed for the x axis, the third is the start and end position for the z axis and the fourth is the speed for the z axis, the fifth is the y position
cosinus_x_start_end: [0, 300]
cosinus_speed_x: 1
cosinus_z_start_end: [100, 300]
cosinus_speed_z: 2
cosinus_y: 200